//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATRS.Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class atrsEntities : DbContext
    {
        public atrsEntities()
            : base("name=atrsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Flight> Flights { get; set; }
        public virtual DbSet<Passenger> Passengers { get; set; }
        public virtual DbSet<Reservation> Reservations { get; set; }
        public virtual DbSet<FlightTrack> FlightTracks { get; set; }
    
        public virtual int MostVisitedCity()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MostVisitedCity");
        }
    
        public virtual int MostVisitedCityGenerate()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MostVisitedCityGenerate");
        }
    }
}
