//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATRS.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public int ReservationNumber { get; set; }
        public Nullable<int> PassengerID { get; set; }
        public string Ticket { get; set; }
        public string FlightNumber { get; set; }
    
        public virtual Flight Flight { get; set; }
        public virtual Passenger Passenger { get; set; }
    }
}
